fix: `VirtualFileEntry::GetEntry` can traverse >64 FATEntries.
Wunkolo/libsai pull request #17
Opened 2023-04-09 06:49 UTC by UserIsntAvailable

Wasn't really related with last PR, so I decided to split it.

If a folder has more than 64 `FATEntries`, the `NextPageIndex` field on the `PageEntry` will indicate on what `Page` the extra entries are located.

And that is all, the code could definitely be better written, but this works ( and I'm not really sure how to improve this without refactoring the whole method ).

2023-04-10 16:44 UTC, Wunkolo commented
Thank you for this! The `Tree` sample does not show it due to `IterateFATBlock` iterating a finite amount of entries like you noted but I can confirm that the `Document` tool successfully iterates a sai document with 256 layer files properly. The only adjustment I think needs to be made is converting the spaces back into tabs and this should be ready to merge and I can re-visit this whole code-base later to fix the `Tree`-iteration issue among others.

2023-04-10 23:59 UTC, Wunkolo requested changes

2023-04-10 23:59 UTC, Wunkolo commented on source/sai.cpp
> +// Check VirtualFileSystem::GetEntry ( Line 591 ) for comments.
I just fixed this issue over on https://github.com/Wunkolo/libsai/commit/04c019823c39c0112d7a7df7f38170c097c568c8!

2023-04-10 23:59 UTC, Wunkolo commented on source/sai.cpp
> +            std::uint32_t NextPageIndex = TablePage.PageEntries[CurPageIndex].NextPageIndex;
Can be marked `const`

2023-04-10 23:59 UTC, Wunkolo commented on source/sai.cpp
> +            std::uint32_t PageIndex = CurPage.FATEntries[CurEntry].PageIndex;
Can be `const`

2023-04-10 23:59 UTC, Wunkolo commented on source/sai.cpp
> +    VirtualPage CurPage;
It seems all the tabs have been replaced with spaces, causing the diff to be very unconcise.

2023-04-11 02:55 UTC, UserIsntAvailable commented on source/sai.cpp
> +// Check VirtualFileSystem::GetEntry ( Line 591 ) for comments.
:+1:

2023-04-11 04:15 UTC, UserIsntAvailable commented
Everything should be fine now. :+1:

2023-04-11 04:34 UTC, merged

2023-04-11 04:34 UTC, Wunkolo commented
Thank you!