feat: add mask decompression to README.
Wunkolo/libsai pull request #19
Opened 2023-05-13 10:01 UTC by UserIsntAvailable

Closes #10 

Funny enough [this was already partially discussed](https://github.com/Wunkolo/libsai/issues/6#issuecomment-527774921), but it was never implemented or documented. So with that information + the `therahedwig` issue, it was quite easy to figure out how masks were laid out ( even though I still de-compiled sai executable to verify ).

2023-05-18 04:08 UTC, Wunkolo requested changes
Thanks for looking into this! This def makes libsai's raster capabilities much more complete now.

2023-05-19 05:07 UTC, UserIsntAvailable commented on README.md
> +If you are trying to `apply` a mask to a layer then the first component is useless. Masks are used to make parts of the parent layer more transparent; only the opacity is needed for that; you can thi
You are right!!! Masks are 16-bit ( technically 15-bit ) per pixel, BUT they are stored on **Big Endian** ( FFS why endianness is such a nightmare ).

If you want to stop reading, that is the TLDR, but if you don't mind reading the rabbit hole that I went to understand all this, then be my guess:

---

## Masks as 16-bit Little Endian

After I implemented the RLE decompression for masks, obviously the next step is to find out what the bytes actually meant. My first instinct was to read the masks as a single 16-bit **Little Endian** pixel, and it seemed to work fine:

_Black zones are the "masked" parts._ 

![image](https://github.com/Wunkolo/libsai/assets/57047985/805a5f6e-663a-48bf-8a99-b534b69390d9)

So I was finally done, right? _Obviously no_

## Masks as G8A8

One of my old sai drawings had a mask that when converted to PNG it was just black, but in sai it was showing just fine ( the explanation of the actual issue here is in the last section ). So after a couple minutes trying to figure out what was wrong, I remembered what you said on issue #10:

> 16447 has a bit pattern 0100000000111111 [...]. The last 6 bits probably actually encodes the pixel intensity.

Then I had the idea of reading Masks as G8A8 ( on the stb_image library this is equivalent to comp=YA ). With G8A8 both the first mask that I tried AND the old sai drawing had a good PNG representation, but instead of black as "masked" parts now it is white:

![image](https://github.com/Wunkolo/libsai/assets/57047985/670bc141-537d-4927-a1ff-61aaee475bc9)

Ok, so I'm finally done now? _Nope_

## Masks as A8 ( ignore the first 8 bits )

Everything is still working, but then I decided to read the [Wikipedia page about Grayscale color depth](https://en.wikipedia.org/wiki/Grayscale) to understand the point of all of this, because I don't have that much experience with color related things ( I guess that is why I struggled so much with this ); I also knew that GIMP ( and Photoshop? ) uses a single alpha value to represent a mask pixel, so sai's "grayscale" pixels felt _weird_ ( I guess sai wants to be more precise? ).

On the linked page then I read:

> The [TIFF](https://en.wikipedia.org/wiki/Tagged_Image_File_Format) and [PNG](https://en.wikipedia.org/wiki/Portable_Network_Graphics) (among other) [image file formats](https://en.wikipedia.org/wiki/Image_file_formats) support 16-bit grayscale natively, although browsers and many imaging programs tend to ignore the low order 8 bits of each pixel. Internally for computation and working storage, image processing software typically uses integer or floating-point numbers of size 16 or 32 bits.

Huh, interesting; what would happen if I then skip the first 8 bits, and read the pixel it as a single 8-bit value. Welp, everything keeps working the exact same, but once again the masked parts are black ( my old sai drawing was also fine ):

![image](https://github.com/Wunkolo/libsai/assets/57047985/a536cbc8-b7a4-41a6-8848-8130957d7236)

So finally, I concluded that the first byte is useless and you only need the second one; I modified the README, send the PR, and everything is good? _Kinda_

## Requested changes

Everything works, but you had one good question, and a really good observation:

1. > Can you explain a bit more about what the use of the first component is here?

I was kinda confident that the first component was just a monochromatic value, but while I was writing the explanation for your question, then I got confused.

If the first component is a monochromatic value, then why the value sometimes is `0` when it shouldn't. Lets take the next 128x32 sai file as example:

![image](https://github.com/Wunkolo/libsai/assets/57047985/f7340339-916e-4e4a-80ff-3ac3a872e341)

Then if I convert this as to a PNG ( mask read as 16-bit little endian ), I will get:

![image](https://github.com/Wunkolo/libsai/assets/57047985/5f34a27a-ccd0-4c58-b595-563c875fcec5)

The mask indeed matches with the sai one, which shows that the first component **it is indeed the grayscale color**, but if this was one of my old drawings, the generated PNG would just have been a full back image. That is kinda odd, why would sai write to this value sometimes and then ignore it other times? ( another reason to believe that G8A8/A8 could be use here ). I tried creating masks with different patterns, pens, colors; nothing helped. 

While trying to come with more "weird" ways to create masks, I recalled my old sai workflow: I do my drawings on sai, then I export it as psd, then, in Photoshop, I apply any effect that sai didn't had ( imagine not having "text" layers ), then finally import that psd file once again to sai. It would make sense that when converting from psd <-> sai or vice-versa, the first component will be zeroed out, because Photoshop just needs the alpha value to create have a mask pixel ( I don't know if that is really true; GIMP only needs an alpha value, so it wouldn't be crazy to think that Photoshop does the same ).

I went ahead and exported one of my sample layer mask file to psd, and converted it back to a sai file, and... **it is indeed the case**; if I read the mask as a 16-bit **Little Endian** pixel, I will have a completely black image, just like in old drawings. Sai might use this byte to do operations on i/f/u16 if the masks are being created _on their software_, but if the file is being imported/exported it will just default it to `0`.

Ok, but how I did though about **Big Endian**?

2. > I would otherwise think that a mask would just be a singular monochromatic value.

The first time that I read that I was like: "That doesn't make no sense, I already read it as a 16-bit ( little endian ) value, and I had the Photoshop problem explained above". So I continued writing this whole essay, then while writing the G8A8 section I found a really interested thing on the next value: `0100000000111111`.

The `01000000` part is 64 in decimal which is the max value that I was claiming as the "alpha" component. Then I quickly realize that I never tested to read masks as 16-bit **Big Endian** values, and as you read at the top, it is indeed big endian... ( **BIG** :facepalm: )

---

Now with all that said ( I can't believe I just wrote a 1000 word essay on a GitHub PR ), if you made it this far, does this make any sense? Maybe everything is just a big coincidence, and this doesn't make sense at all. Anyways, I guess the moral of the history is "When in doubt, check the endianness"; I should probably tape that on my wall, because is not the first time that this had happen to me, sadly...

2023-05-19 05:08 UTC, UserIsntAvailable commented on README.md
> +Mask data is stored the same way that `raster` data, but it is 16bpp instead of 32bpp; so rather than `BGRA` as channels, masks contain `greyscale` pixels where:
Wouldn't it be 7bpp of alpha since 64 has a bit pattern of `0b01000000`?

2023-05-19 05:21 UTC, UserIsntAvailable commented
I changed the readme to indicate the new info. Maybe there something else that should be added?

2023-05-20 02:13 UTC, Wunkolo commented on README.md
> +If you are trying to `apply` a mask to a layer then the first component is useless. Masks are used to make parts of the parent layer more transparent; only the opacity is needed for that; you can thi
Oh wow thank you for this deep analysis! So it is certainly big-endian? That's really weird to suddenly have big-endian pixel data out of no where for a software that only ever runs on little-endian machines, but maybe there is some efficiency gains to be had for some SIMD instructions or something by having it be in a big-endian layout like being able to early-out-test certain pixel values by just checking an upper or lower byte or something. I'll have to dig up my much older and complete IDA Pro database to see if that's really the case. But this seems great enough to move forward with for now!

If it's 16-bits, but it only seems to use the "lower" 15-bits, then it's likely that it is just a _signed_ 16-bit variable that never touches the upper bit since there is no case where the pixel value is negative. This makes me very skeptical as to how the regular color-data is laid out.

The software claims to be 16bpc but I only found an 8bpc RGBA data for layers that I was unable to find proof of:
![image](https://github.com/Wunkolo/libsai/assets/644247/1ed3ca04-4ada-46f2-8356-7ce230158eab)

_but_ **there are 4 additional steams of "unknown" data that I skip here after reading the 8bpc color-data** that I could not decipher the meaning of and was able to stop at the 8bpc data for my use-case. It's likely that this is _also_ RGBA data with 16bpc of `int32` pixel data, and it keeps around the 8bpc version as well for certain image operations or caching or something.
https://github.com/Wunkolo/libsai/blob/2797c13ec1226170f1ac63d767ab1f997fd1991e/samples/Document.cpp#L245-L254

Thank you very much again for your research!

2023-05-20 02:13 UTC, Wunkolo commented on README.md
> +Mask data is stored the same way that `raster` data, but it is 16bpp instead of 32bpp; so rather than `BGRA` as channels, masks contain `greyscale` pixels where:
You're right! Off by a bit.

2023-05-20 02:27 UTC, Wunkolo requested changes
Just some more clarification stuff given what we know so far. Otherwise the principal of your findings are all great!

2023-05-20 02:27 UTC, Wunkolo commented on README.md
> +Mask data is stored the same way that `raster` data, but it is 16bpp instead of 32bpp; so rather than `BGRA` as channels, masks are 16-bit ( or technically 15-bit ) `greyscale` big endian pixels.
I think you mean `but it is 16bpc instead of 8bpc`. `bpc` and `bpp` can be confusing at times.

* `RGBA` at 8bpc(bits per _channel_) means 32bpp(bits per _pixel_)
* `A` at 16bpc(bits per _channel_) means 16bpp(bits per _pixel_)

It should be fine to just say that it is 16bpc without comparing it to the other color-depths since [now I am skeptical of there being 16-bpc color-data somewhere too now](https://github.com/Wunkolo/libsai/blob/2797c13ec1226170f1ac63d767ab1f997fd1991e/samples/Document.cpp#L245-L254).

2023-05-20 02:27 UTC, Wunkolo commented on README.md
> +This is a snippet with the current implementation of `Document.cpp`, but using `uint16_t` and a smaller `Compress` and `Decompressed` buffer instead:
I would just say that it is `int16_t` for now until we are certain if it is signed or unsigned. I'm starting to feel like it is a signed `int16` even though there is never a use-case for negative mask-values. It was likely designed this way due to the 16-bit element SIMD instruction-set that the data-layout is anticipating.

The application uses Intel MMX for all of its image kernels and mentions this on the site.
![image](https://github.com/Wunkolo/libsai/assets/644247/1b337282-2ff4-445d-9f0b-f1dbad15063a)

[MMX primarily supports _signed_ 16-bit types](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=MMX). Which would likely be a reason for all of this 16bpc image data to also be 16-bit signed integers.

2023-05-20 13:56 UTC, UserIsntAvailable commented on README.md
> +If you are trying to `apply` a mask to a layer then the first component is useless. Masks are used to make parts of the parent layer more transparent; only the opacity is needed for that; you can thi
> It's likely that this is also RGBA data with 16bpc of int32 pixel data

So if I understand this correctly, instead of storing B16G16R16A16, sai might store it as B8G8R8A8B8G8R8A8? That actually would make a lot of sense. Since sai uses MMX, it would be better to have 2 lanes of B8G8R8A8 then do vertical operations with both of them, instead of having 2 lanes of B16G16 and R16A16. It could also help in situations where they only need 8-bit components.

Gonna look into this later, but it sound promising.

2023-05-20 14:59 UTC, UserIsntAvailable commented
Everything should be good now.

2023-05-21 01:12 UTC, merged